### ISSUE TITLE
Aria配置

### ISSUE THREAD

**Issue by moonan3019** [injahow/user.js#10]
麻烦问一下这个RPC我想指到我本地其他电脑上来通过aria2下载，
 我试了把IP设置成本地的那台机器 并添加了白名单，
 端口改成6800 但是提示我RPC参数错误 我该如何配置呢
![Uploading image.png…]()

**Comment by injahow** [comment]
局域网域名配置: http://192.168.1.1 或 ws://192.168.1.1
点击确定后会弹出ariang网页控制台，如果连接不成功可在ariang进行设置，如下图
![image](https://user-images.githubusercontent.com/42839062/163674306-a5609981-9140-433a-93e9-5803276bf65b.png)

**Comment by moonan3019** [comment]
<img width="489" alt="屏幕截图 2022-04-16 201432" src="https://user-images.githubusercontent.com/70310435/163674550-09bd5625-7bf7-4b8a-8df2-f5ff2a220a76.png">
<img width="1748" alt="屏幕截图 2022-04-16 201451" src="https://user-images.githubusercontent.com/70310435/163674554-38dcdbc8-3db7-4f82-9df2-9d675f120b53.png">
感谢您的回答 我的配置是这样的 问题出在哪里呢

**Comment by injahow** [comment]
还是建议ariang地址使用ariang网站域名，脚本使用window.bp_aria2_window对象传递下载任务，不知道这种方式能否正常执行
你的环境下，点击下载后脚本能自动打开file:///ariang页面吗

**Comment by moonan3019** [comment]
我查看了一下 链接是成功的 但是点击下载之后确实没有打开ng页面

**Comment by moonan3019** [comment]
http://ariang.mayswind.net/latest/#!/downloading 我把ng指引到这个界面 点击下载后会跳到这页面但是下载任务没有创建

**Comment by injahow** [comment]
> http://ariang.mayswind.net/latest/#!/downloading 我把ng指引到这个界面 点击下载后会跳到这页面但是下载任务没有创建

地址请填写到hash之前，如 http://ariang.mayswind.net/latest/

**Comment by moonan3019** [comment]
好的 按您说的 问题得到了解决 十分感谢您的帮助
