### ISSUE TITLE
无法下载1080P60帧的视频

### ISSUE THREAD

**Issue by lubutong** [injahow/user.js#32]
有大会员+在下载中选择1080P60帧的情况下，下载的视频依然为1080P30帧
![image](https://user-images.githubusercontent.com/110240479/196426219-068b80d2-c226-40a3-9114-1d85243a7046.png)
![image](https://user-images.githubusercontent.com/110240479/196426331-95460b87-0a85-4514-8539-552598759d95.png)
![image](https://user-images.githubusercontent.com/110240479/196426465-a3b9d34a-8252-4084-8698-e7ca6144cc85.png)

**Comment by injahow** [comment]
视频格式问题，只有dash存在1080p60

**Comment by lubutong** [comment]
> 

![image](https://user-images.githubusercontent.com/110240479/196684240-4080b53e-dafa-4c09-9fe7-bb099ef48109.png)
![image](https://user-images.githubusercontent.com/110240479/196684328-0fb0422d-7bc7-418e-8451-311d380621f2.png)
还是只有30帧

**Comment by injahow** [comment]
那应该是接口改了吧，等我有空在看看 _(-ω- 」∠)_

**Comment by injahow** [comment]
已修复
