### ISSUE TITLE
iOS 浏览器适配

### ISSUE THREAD

**Issue by yangliu-1995** [injahow/user.js#41]
你好，我在做一款支持油猴的iOS浏览器，跑到您的做脚本时报了如下错误，请问您有联系方式吗？
`TypeError: vb.bvid is not a function. (In 'vb.bvid(page)', 'vb.bvid' is undefined)`

**Comment by injahow** [comment]
重新拉取一遍代码试试，这个是上个月问题

**Comment by injahow** [comment]
> 可以交换一下联系方式吗 我的邮箱是 yangliu-1995#outlook.com

有问题可以直接发邮件，在github首页应该有，我有时间就看看，另外你这个是打包后的吧，源代码没看吗

**Comment by yangliu-1995** [comment]
抱歉没注意到你的邮箱 我明天对着源代码调一下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: injahow ***@***.***>
发送时间: Wednesday, November 23, 2022 11:19:56 PM
收件人: injahow/user.js ***@***.***>
抄送: yangliu-1995 ***@***.***>; Author ***@***.***>
主题: Re: [injahow/user.js] iOS 浏览器适配 (Issue #41)


可以交换一下联系方式吗 我的邮箱是 yangliu-1995#outlook.com

有问题可以直接发邮件，在github首页应该有，我有时间就看看，另外你这个是打包后的吧，源代码没看吗

―
